artifact_uri: ../mlflow/1/eb92f0d6fe09499b9b79559a880bae1b/artifacts
end_time: 1602976486648
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: eb92f0d6fe09499b9b79559a880bae1b
run_uuid: eb92f0d6fe09499b9b79559a880bae1b
source_name: ''
source_type: 4
source_version: ''
start_time: 1602971276944
status: 3
tags: []
user_id: root
