artifact_uri: ../mlflow/1/d9ada5308cbd461f93acd80c46d27aa5/artifacts
end_time: 1602872678862
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d9ada5308cbd461f93acd80c46d27aa5
run_uuid: d9ada5308cbd461f93acd80c46d27aa5
source_name: ''
source_type: 4
source_version: ''
start_time: 1602862121256
status: 3
tags: []
user_id: root
