artifact_uri: ../mlflow/1/0307ceee6c6c407d88a8c8b6fd1643f1/artifacts
end_time: 1603021002720
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 0307ceee6c6c407d88a8c8b6fd1643f1
run_uuid: 0307ceee6c6c407d88a8c8b6fd1643f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1603018897991
status: 3
tags: []
user_id: root
