artifact_uri: ../mlflow/1/f0e5ec50b4e14e7db1bd5e5f87f8014e/artifacts
end_time: 1603028811309
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: f0e5ec50b4e14e7db1bd5e5f87f8014e
run_uuid: f0e5ec50b4e14e7db1bd5e5f87f8014e
source_name: ''
source_type: 4
source_version: ''
start_time: 1603027671924
status: 3
tags: []
user_id: root
