artifact_uri: ../mlflow/1/4b31e79ac8b74b39a3304ba3e6ddee75/artifacts
end_time: 1603017803808
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4b31e79ac8b74b39a3304ba3e6ddee75
run_uuid: 4b31e79ac8b74b39a3304ba3e6ddee75
source_name: ''
source_type: 4
source_version: ''
start_time: 1603007632322
status: 3
tags: []
user_id: root
