artifact_uri: ../mlflow/1/3f99e12353d44c4abc5c3cee9ef89ef3/artifacts
end_time: 1603018897984
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 3f99e12353d44c4abc5c3cee9ef89ef3
run_uuid: 3f99e12353d44c4abc5c3cee9ef89ef3
source_name: ''
source_type: 4
source_version: ''
start_time: 1603017803816
status: 3
tags: []
user_id: root
